// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI commands (migrate, studio) use the direct/unpooled connection —
    // the app itself connects via the pooled DATABASE_URL (see src/lib/db.ts).
    url: process.env["DIRECT_URL"],
  },
});
