-- CreateEnum
CREATE TYPE "CoachingMode" AS ENUM ('OFFLINE', 'ONLINE', 'HYBRID');

-- CreateEnum
CREATE TYPE "CompetitiveExam" AS ENUM ('NEET', 'JEE_MAIN', 'JEE_ADVANCED', 'CUET', 'CLAT', 'TET', 'BANK_SSC_RAILWAYS', 'OTHER');

-- AlterEnum
ALTER TYPE "Role" ADD VALUE 'COACHING_CENTRE';

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "TeachingSubject" ADD VALUE 'PG_TAMIL';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_SPECIAL_TAMIL';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_ENGLISH';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_HINDI';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_ARABIC';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_FRENCH';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_MATHS';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_PHYSICS';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_CHEMISTRY';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_BIOLOGY';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_BOTANY';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_ZOOLOGY';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_BIO_CHEMISTRY';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_MICRO_BIOLOGY';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_ACCOUNTANCY';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_COMMERCE';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_HISTORY';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_ECONOMICS';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_BUSINESS_MATHS';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_STATISTICS';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_COMPUTER_SCIENCE';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_POLITICAL_SCIENCE';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_NURSING';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_PSYCHOLOGY';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_SOCIOLOGY';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_VOCATIONAL_OFFICE_MANAGEMENT';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_VOCATIONAL_GENERAL_NURSING';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_VOCATIONAL_NUTRITION_DIETETICS';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_VOCATIONAL_BASIC_ENGINEERING';
ALTER TYPE "TeachingSubject" ADD VALUE 'PG_VOCATIONAL_TEXTILE_TECHNOLOGY';
ALTER TYPE "TeachingSubject" ADD VALUE 'NEET_EXPERT_BIOLOGY';
ALTER TYPE "TeachingSubject" ADD VALUE 'NEET_EXPERT_BOTANY';
ALTER TYPE "TeachingSubject" ADD VALUE 'NEET_EXPERT_PHYSICS';
ALTER TYPE "TeachingSubject" ADD VALUE 'NEET_EXPERT_CHEMISTRY';
ALTER TYPE "TeachingSubject" ADD VALUE 'NEET_EXPERT_ZOOLOGY';
ALTER TYPE "TeachingSubject" ADD VALUE 'JEE_MAIN_EXPERT_PHYSICS';
ALTER TYPE "TeachingSubject" ADD VALUE 'JEE_MAIN_EXPERT_CHEMISTRY';
ALTER TYPE "TeachingSubject" ADD VALUE 'JEE_MAIN_EXPERT_MATHS';
ALTER TYPE "TeachingSubject" ADD VALUE 'JEE_ADVANCED_EXPERT_PHYSICS';
ALTER TYPE "TeachingSubject" ADD VALUE 'JEE_ADVANCED_EXPERT_CHEMISTRY';
ALTER TYPE "TeachingSubject" ADD VALUE 'JEE_ADVANCED_EXPERT_MATHS';
ALTER TYPE "TeachingSubject" ADD VALUE 'TET_PAPER_I_EXPERT_TAMIL';
ALTER TYPE "TeachingSubject" ADD VALUE 'TET_PAPER_I_EXPERT_ENGLISH';
ALTER TYPE "TeachingSubject" ADD VALUE 'TET_PAPER_I_EXPERT_MATHS';
ALTER TYPE "TeachingSubject" ADD VALUE 'TET_PAPER_I_EXPERT_SCIENCE';
ALTER TYPE "TeachingSubject" ADD VALUE 'TET_PAPER_I_EXPERT_SOCIAL';
ALTER TYPE "TeachingSubject" ADD VALUE 'TET_PAPER_II_EXPERT_TAMIL';
ALTER TYPE "TeachingSubject" ADD VALUE 'TET_PAPER_II_EXPERT_ENGLISH';
ALTER TYPE "TeachingSubject" ADD VALUE 'TET_PAPER_II_EXPERT_MATHS';
ALTER TYPE "TeachingSubject" ADD VALUE 'TET_PAPER_II_EXPERT_SCIENCE';
ALTER TYPE "TeachingSubject" ADD VALUE 'TET_PAPER_II_EXPERT_SOCIAL';

-- AlterTable
ALTER TABLE "JobVacancy" ADD COLUMN     "coachingMode" "CoachingMode";

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "coachingMode" "CoachingMode",
ADD COLUMN     "examsOffered" "CompetitiveExam"[] DEFAULT ARRAY[]::"CompetitiveExam"[];
